name: Release

on:
  push:
    branches:
      - "main"

jobs:
  Release:
    name: "Release"

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: "Build on ${{ matrix.os }}"
        run: cargo build --release --verbose
      
      - name: "Release on Windows"
        id: release_on_win
        if: ${{ matrinx.os }} == "windows-latest"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            ./target/release/${{ github.event.repository.name }}.exe

      - name: "Release on Mac"
        id: release_on_mac
        if: ${{ matrinx.os }} == "macos-latest"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            ./target/release/${{ github.event.repository.name }}
